---
- name: Include systemd task for Ubuntu
  ansible.builtin.include_tasks: systemd.yml
  when: ansible_distribution == 'Ubuntu'

- name: Import AdGuardHome task
  ansible.builtin.include_tasks: adguardhome.yml
