---
- name: Set 127.0.0.1 to DNS
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNS='
    line: 'DNS=127.0.0.1'

- name: Set "no" to DNSStubListener
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#DNSStubListener='
    line: 'DNSStubListener=no'

- name: Reload systemd-resolved configuration
  ansible.builtin.systemd:
    daemon_reload: yes
    state: restarted
    name: systemd-resolved
  changed_when: false