---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_pkg_mgr == "apt"

  tasks:
    - name: Install "docker" PIP package for not Alpine Linux
      ansible.builtin.include_role:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
      when:
        - ansible_distribution != "Alpine"
    
    - name: Install "docker" PIP package for Alpine Linux
      community.general.apk:
        name: py3-docker-py
        state: latest
        no_cache: true
      when:
        - ansible_distribution == "Alpine"

    - name: Include install docker role
      ansible.builtin.include_role:
        name: "kirill_zak.docker"

    - name: Include kirill_zak.adguardhome_docker
      ansible.builtin.include_role:
        name: "kirill_zak.adguardhome_docker"
        tasks_from: main.yml
